In [2]:
import numpy as np

In [9]:
A = np.array([1,0,1])

In [12]:
print(A)

[1 0 1]


In [40]:
np.reshape(A, (3,1))
print(A.shape)

(3,)


In [5]:
np.sum(A == 1)

2

In [28]:
B = np.array([[1,2,3,5],[4,5,6,10],[7,8,9, 15]])

In [29]:
print(B)

[[ 1  2  3  5]
 [ 4  5  6 10]
 [ 7  8  9 15]]


In [30]:
mu= np.dot(B.T, A == 0)
print(mu)

[ 4  5  6 10]


In [31]:
B - mu

array([[-3, -3, -3, -5],
       [ 0,  0,  0,  0],
       [ 3,  3,  3,  5]])

In [32]:
print((B-mu).shape)
print(A.shape)

(3, 4)
(3,)


In [42]:
(B-mu).T * (A == 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
(B-mu).T * (A == 1)

array([[-3,  0,  3],
       [-3,  0,  3],
       [-3,  0,  3],
       [-5,  0,  5]])

In [38]:
A.shape

(3,)

In [3]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [4]:
print(A-B)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [6]:
print(np.linalg.norm(A[0]-B[0]))

10.770329614269007


In [7]:
print(np.linalg.norm((A-B)[0]))

10.770329614269007


In [8]:
W = np.zeros((3,3))

In [10]:
for i in range(3):
    W[i][i] = np.linalg.norm((A-B)[i])

In [11]:
print(W)

[[10.77032961  0.          0.        ]
 [ 0.          2.82842712  0.        ]
 [ 0.          0.         10.77032961]]


In [12]:
A - [[1,2,3]]

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])