In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[-1,-1,-1],[3,4,5]])

In [3]:
print(A)
print(A > 0)

[[ 1  2  3]
 [-1 -1 -1]
 [ 3  4  5]]
[[ True  True  True]
 [False False False]
 [ True  True  True]]


In [4]:
print((A > 0).astype(int))

[[1 1 1]
 [0 0 0]
 [1 1 1]]


In [5]:
print(np.flip(A, axis=0))
print(np.sum(A, axis=0))

[[ 3  4  5]
 [-1 -1 -1]
 [ 1  2  3]]
[3 5 7]


In [6]:
print(np.flip(A, axis=1))

[[ 3  2  1]
 [-1 -1 -1]
 [ 5  4  3]]


In [8]:
print(A)

[[ 1  2  3]
 [-1 -1 -1]
 [ 3  4  5]]


In [9]:
print(A.argmax())

8


In [10]:
np.unravel_index(A.argmax(), A.shape)

(2, 2)

In [11]:
A = np.array([[4,4,4],[3,3,3],[2,2,2]])

In [12]:
print(A.argmax())

0
